# Setup
title:        Galene
tagline:      Correcting for physiological motion in functional imaging data
baseurl:      ""
paginate:     1

# Current version
version:      2.0.2


# About/contact
author:
  name:       Sean Warren
  url:        http://flimfit.org/galene 


# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown