# Setup
title:        Galene
tagline:      Correcting for physiological motion in functional imaging data
baseurl:      ""
paginate:     1

# Current version
version:      2.2.0


# About/contact
author:
  name:       Sean Warren
  url:        https://galene.flimfit.org 


# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown